# 1.create a 3x3x3 matrix with random values .

In [1]:
import random

matrix = [[[random.randint(1, 100) for _ in range(3)] for _ in range(3)] for _ in range(3)]

for i in range(3):
    for j in range(3):
        for k in range(3):
            print(matrix[i][j][k], end=' ')
        print()
    print()


10 76 33 
12 57 91 
80 97 27 

14 4 22 
27 8 24 
77 92 10 

91 59 28 
78 47 40 
10 24 14 



# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
matrix = [[0 for _ in range(5)] for _ in range(5)]

for i in range(5):
    for j in range(5):
        if i == j + 1:
            matrix[i][j] = i + 1

for row in matrix:
    print(row)


[0, 0, 0, 0, 0]
[2, 0, 0, 0, 0]
[0, 3, 0, 0, 0]
[0, 0, 4, 0, 0]
[0, 0, 0, 5, 0]


# 3.create 8x8 matrix and fill it with a checkboard pattern.

In [3]:
matrix = [[(i + j) % 2 for i in range(8)] for j in range(8)]

for row in matrix:
    print(" ".join(map(str, row)))


0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0


# 4.Normalize a 5x5 random matrix

In [4]:
import numpy as np

matrix = np.random.rand(5, 5)
normalized_matrix = (matrix - matrix.min()) / (matrix.max() - matrix.min())

print("Original Matrix:")
print(matrix)

print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.20513413 0.25839319 0.8878114  0.19948308 0.17780394]
 [0.77246147 0.10713022 0.37349579 0.42979506 0.8999113 ]
 [0.19260109 0.07296897 0.4590406  0.23094683 0.8478238 ]
 [0.84878227 0.7792733  0.47458066 0.24696729 0.43644031]
 [0.02251064 0.81152816 0.82172649 0.33687466 0.85458363]]

Normalized Matrix:
[[0.20814149 0.26884245 0.98620937 0.20170083 0.17699246]
 [0.85474158 0.09644349 0.40002836 0.46419434 1.        ]
 [0.19385722 0.05750888 0.49752636 0.23756101 0.9406343 ]
 [0.9417267  0.86250523 0.51523784 0.25582002 0.47176813]
 [0.         0.89926707 0.91089041 0.35829015 0.94833868]]


# 5.How to find common values between two arrays?

In [5]:
array1 = [1, 2, 3, 4, 5]
array2 = [3, 4, 5, 6, 7]

common_values = list(set(array1) & set(array2))

print("Common values:", common_values)


Common values: [3, 4, 5]


# 6. How to get the dates of ywaturday ,today and tomorrow?

In [6]:
from datetime import datetime, timedelta

today = datetime.now()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday.date())
print("Today:", today.date())
print("Tomorrow:", tomorrow.date())


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7. Consider tow random array A and B , check if they are equal?

In [7]:
import numpy as np

A = np.random.rand(5)
B = np.random.rand(5)

are_equal = np.array_equal(A, B)

print("Arrays A and B are equal:", are_equal)


Arrays A and B are equal: False


# 8.Create random vector of size 10 and replace the maximum value by 0

In [8]:
import numpy as np

vector = np.random.rand(10)
vector[np.argmax(vector)] = 0

print(vector)


[0.55402839 0.         0.0311005  0.49717502 0.52871894 0.92589161
 0.73536892 0.09696639 0.2435251  0.07878238]


# 9. How to print all the values of an array?

In [9]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])

for value in array:
    print(value)


1
2
3
4
5


# 10. Subtract the mean of each row of a matrix.

In [10]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

result = matrix - matrix.mean(axis=1, keepdims=True)

print(result)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeaded indices)?

In [11]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])
indices = np.array([1, 3, 1, 4, 2])

vector[indices] += 1

print(vector)


[1 3 4 5 6]


# 12.How to get the diagonal of a dot product?

In [12]:
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.diag(np.dot(matrix1, matrix2))

print(result)


[19 50]


# 13.How to find the most frequent value in an array?

In [13]:
import numpy as np

array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

most_frequent_value = np.bincount(array).argmax()

print("Most frequent value:", most_frequent_value)


Most frequent value: 4


# 14.How to get the n largest values of an array

In [14]:
import numpy as np

array = np.array([4, 2, 9, 7, 1, 6, 8, 5, 3])

n_largest_values = np.partition(array, -3)[-3:]

print("N largest values:", n_largest_values)


N largest values: [7 8 9]


# 15.How to create a record array from a regular array?

In [15]:
import numpy as np

regular_array = np.array([("Alice", 25), ("Bob", 30), ("Charlie", 35)], dtype=[("name", "U10"), ("age", int)])
record_array = np.rec.array(regular_array)

print(record_array)


[('Alice', 25) ('Bob', 30) ('Charlie', 35)]


# 16.How to swap two rows of an array?

In [16]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

array[[0, 1]] = array[[1, 0]]

print(array)


[[4 5 6]
 [1 2 3]
 [7 8 9]]


# 17.Write python code to reshape to the next dimentsion of numpy array?

x = np.array([[23,34,121],[23,22,67],[686,434,123]])

In [17]:
import numpy as np

x = np.array([[23, 34, 121],
              [23, 22, 67],
              [686, 434, 123]])

reshaped_array = x.reshape(-1, 1)

print(reshaped_array)


[[ 23]
 [ 34]
 [121]
 [ 23]
 [ 22]
 [ 67]
 [686]
 [434]
 [123]]
